#!/bin/bash

# ERB Template Testing Script
# Tests the ERB template functionality without timeouts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PUPPETC="$SCRIPT_DIR/../compiler/puppetc-compile"
OUTPUT_DIR="$SCRIPT_DIR/output"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "🧪 ERB Template Test Suite"
echo "=========================="

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Test counters
total_tests=0
passed_tests=0

run_test() {
    local test_name="$1"
    local manifest="$2"
    local template_target="$3"
    local facts_file="$4"
    local expected_content="$5"
    
    echo -n "Testing $test_name... "
    total_tests=$((total_tests + 1))
    
    # Run from project root directory to get correct relative paths
    pushd "$SCRIPT_DIR/.." > /dev/null
    if output=$(./compiler/puppetc-compile --eval --node web01 --facts "$facts_file" --template "$template_target" "$manifest" 2>&1); then
        popd > /dev/null
        # Extract the template output section
        template_output=$(echo "$output" | sed -n '/=== ERB TEMPLATE OUTPUT ===/,/=== END ERB TEMPLATE OUTPUT ===/p' | sed '1d;$d')
        
        # Check if expected content is found (use fixed string match)
        if echo "$template_output" | grep -F -q "$expected_content"; then
            echo -e "${GREEN}✓ PASS${NC}"
            passed_tests=$((passed_tests + 1))
            echo "$output" > "$OUTPUT_DIR/${test_name}.out"
        else
            echo -e "${RED}✗ FAIL${NC} - Expected content not found"
            echo "Expected: $expected_content"
            echo "Got template output:"
            echo "$template_output" | sed 's/^/    /'
            echo "$output" > "$OUTPUT_DIR/${test_name}.fail"
        fi
    else
        popd > /dev/null
        echo -e "${RED}✗ FAIL${NC} - Command failed"
        echo "Error output:"
        echo "$output" | sed 's/^/    /'
        echo "$output" > "$OUTPUT_DIR/${test_name}.fail"
    fi
}

echo ""
echo "Running ERB Template Tests..."
echo ""

# Test 1: Basic ERB functionality
run_test "basic_erb" \
    "tests/puppet/simple_erb_test.pp" \
    "apache-config" \
    "tests/facts/sample_facts.json" \
    "ServerAdmin webmaster@example.org"

# Test 2: Variable interpolation from facts
run_test "facts_interpolation" \
    "tests/puppet/simple_erb_test.pp" \
    "apache-config" \
    "tests/facts/sample_facts.json" \
    "Generated by Puppet for web01"

# Test 3: Operating system facts
run_test "os_facts" \
    "tests/puppet/simple_erb_test.pp" \
    "apache-config" \
    "tests/facts/sample_facts.json" \
    "Environment: Ubuntu 20.04"

# Test 4: Service name from Puppet variables
run_test "puppet_variables" \
    "tests/puppet/simple_erb_test.pp" \
    "apache-config" \
    "tests/facts/sample_facts.json" \
    "Service: apache2"

# Test 5: Port configuration
run_test "port_config" \
    "tests/puppet/simple_erb_test.pp" \
    "apache-config" \
    "tests/facts/sample_facts.json" \
    "VirtualHost *:80"

echo ""
echo "=========================================="
echo -e "ERB Test Results: ${passed_tests}/${total_tests} tests passed"

if [ $passed_tests -eq $total_tests ]; then
    echo -e "${GREEN}✅ All ERB tests passed!${NC}"
    exit 0
else
    echo -e "${RED}❌ Some ERB tests failed. Check output/ for details.${NC}"
    exit 1
fi