#!/bin/bash

# Auto-Build Environment Setup for SSL/TLS Implementation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Puppet-C SSL/TLS Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check for required tools
for tool in autoconf automake libtool pkg-config gcc make docker-compose; do
    if ! command -v $tool &> /dev/null; then
        echo -e "${RED}ERROR: $tool not found${NC}"
        echo "Please install $tool before continuing"
        exit 1
    fi
done

# Check for required libraries
for lib in openssl libcurl tree-sitter ruby sqlite3; do
    if ! pkg-config --exists $lib 2>/dev/null; then
        echo -e "${YELLOW}WARNING: $lib not found via pkg-config${NC}"
        echo "Library may be installed but not in pkg-config path"
    fi
done

echo -e "${GREEN}Dependencies checked${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."

# Generate build system if needed
if [ ! -f configure ]; then
    echo "Generating build system with autoreconf..."
    autoreconf -fi || {
        echo -e "${RED}Failed to generate build system${NC}"
        exit 1
    }
fi

# Configure if needed
if [ ! -f Makefile ]; then
    echo "Running configure..."
    ./configure || {
        echo -e "${RED}Configure failed${NC}"
        exit 1
    }
fi

# Build
echo "Compiling..."
make -j$(nproc) || {
    echo -e "${RED}Build failed${NC}"
    exit 1
}

echo -e "${GREEN}Build complete${NC}"

# ============================================
# START DOCKER SERVICES
# ============================================

echo ""
echo "Starting Docker services..."

# Build Docker images
echo "Building Docker images..."
docker-compose build || {
    echo -e "${RED}Docker build failed${NC}"
    exit 1
}

# Start server
echo "Starting puppetc-server..."
docker-compose up -d server || {
    echo -e "${RED}Failed to start server${NC}"
    exit 1
}

wait_for_service 8140 "puppetc-server"

# Start agent shell (for interactive testing)
echo "Starting agent shell..."
docker-compose up -d agent-shell || {
    echo -e "${RED}Failed to start agent shell${NC}"
    exit 1
}

# ============================================
# VERIFY SETUP
# ============================================

echo ""
echo "Verifying setup..."

# Check server is responding
if curl -f -s http://localhost:8140/status > /dev/null 2>&1; then
    echo -e "${GREEN}Server is responding${NC}"
else
    echo -e "${YELLOW}Warning: Server not responding on HTTP (may be HTTPS-only after TLS implementation)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  puppetc-server:  http://localhost:8140 (will be https:// after TLS implementation)"
echo "  agent-shell:     docker-compose exec agent-shell bash"
echo ""
echo "Useful commands:"
echo "  View server logs:  docker-compose logs -f server"
echo "  Run agent:         docker-compose run agent"
echo "  Agent shell:       docker-compose exec agent-shell bash"
echo "  Stop services:     docker-compose down"
echo "  Rebuild:           docker-compose build"
echo ""
echo "Certificate locations (after TLS implementation):"
echo "  Server CA:         /etc/puppetc/ssl/ca/ca_crt.pem"
echo "  Server CA key:     /etc/puppetc/ssl/ca/ca_key.pem"
echo "  Agent certs:       /var/lib/puppetc/ssl/certs/"
echo "  Agent keys:        /var/lib/puppetc/ssl/private_keys/"
echo ""
